### ISSUE TITLE
When having multiple soundsBaseUrls its not working

### ISSUE THREAD

**Issue by bayerlse** [chrisweb/web-audio-api-player#24]
## Expected behavior

The player can't play files from different domains

## Actual behavior

When playing a queue, only the domain of the first audio seems to be allowed. Audios in the queue with other domains wont be loaded. 

## Steps to reproduce

```ts
const webAudioApiPlayer = new Player();

const playlist: ISoundAttributes[] = [
            {
                source: { url: "https://domain_one.com/test.mp3", codec: 'mp3' },
                id: "id_one"
            },
            {
                source: { url: "https://domain_two.com/test.mp3", codec: 'mp3' },
                id: "id_two"
            },
        ];
        
playlist.forEach((sound, index) => webAudioApiPlayer.addSoundToQueue({ soundAttributes: sound }));

webAudioApiPlayer.play()
```

## Browser

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

## Errors

After the first audio played: 

`index.js:832 Uncaught (in promise) Error: no more sounds in array`

**Comment by bayerlse** [comment]
Ok, found out, that if you have `playNextOnEnded`enabled, it always skips the next sound. So in my case (where always the second sound was from another domain) it has nothing todo with the domain. 

I just saw that `_onEnded` and ´_getSoundFromQueue` will interfere and add +1 twice :(

**Comment by chrisweb** [comment]
thank you for the bug report, I need to investigate this, I will try to look into this soon
